In [15]:
import os
import json
import numpy as np

for filename in os.listdir("."):
    if filename.endswith("json") and filename != "linemod_template_gt.json":
        with open(filename,"r") as f:
            gt_template = json.load(f)
            
        
        for key in gt_template.keys():
            for obj_id in range(len(gt_template[key])):
                tmp_R = np.array(gt_template[key][obj_id]["cam_R_m2c"]).reshape(3,3)*1000
                gt_template[key][obj_id]["cam_R_m2c"] = tmp_R.tolist()
        
        
        
        with open(filename,"w") as f:
             json.dump(gt_template, f)

In [16]:
for filename in os.listdir("."):
    if filename.endswith("json") and filename != "linemod_template_gt.json":
        with open(filename,"r") as f:
            gt_template = json.load(f)
            
        
        for key in gt_template.keys():
            for obj_id in range(len(gt_template[key])):
                print(np.array(gt_template[key][obj_id]["cam_R_m2c"]).reshape((3,3)))

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
[[ 0.95105806 -0.30901225  0.        ]
 [ 0.30605782  0.9419651  -0.13795056]
 [ 0.04262841  0.13119899  0.99043912]]
[[-0.95105806 -0.30901225 -0.        ]
 [ 0.30605782 -0.9419651  -0.13795056]
 [ 0.04262841 -0.13119899  0.99043912]]
[[-0.58778075  0.80902026  0.        ]
 [-0.8012853  -0.58216104 -0.13795065]
 [-0.11160487 -0.08108473  0.9904391 ]]
[[ 0.58778075  0.80902026  0.        ]
 [-0.8012853   0.58216104 -0.13795065]
 [-0.11160487  0.08108473  0.9904391 ]]
[[ 0.         -1.          0.        ]
 [ 0.99043894  0.         -0.13795184]
 [ 0.13795184  0.          0.99043894]]
[[-0.95105481  0.30902224  0.        ]
 [-0.30117094 -0.92689146 -0.22398279]
 [-0.06921566 -0.21301991  0.9745931 ]]
[[ 0.95105481  0.30902224  0.        ]
 [-0.30117094  0.92689146 -0.22398279]
 [-0.06921566  0.21301991  0.9745931 ]]
[[ 0.58778458 -0.80901748  0.        ]
 [ 0.78846274  0.57285071 -0.2239834 ]
 [ 0.18120649  0.13165399  0.97459296]]
[[-0.58778